INSERT INTO templates (slug, name, description, definition, default_data) VALUES
(
  'classic',
  'Класичний',
  'Витончений редакторський дизайн з рукописним шрифтом',
  '{"id":"classic","name":"Класичний","description":"Витончений редакторський дизайн з рукописним шрифтом","defaultColors":{"primary":"#FBF7EE","text":"#2C2416","accent":"#D4A574"},"thumbnail":{"bg":"#FBF7EE","text":"#2C2416","accent":"#D4A574","swatch1":"#F5E6D3","swatch2":"#D4A574","swatch3":"#8B7355","fontClass":"thumb-script-classic","headerText":"Софія та Михайло","fontFaces":"@import url(''https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap''); .thumb-script-classic { font-family: \"Great Vibes\", cursive; }"},"theme":{"fontImports":"https://fonts.googleapis.com/css2?family=Geologica:wght@100..900&family=Great+Vibes&display=swap","background":"#FBF7EE","surface":"#F5E6D3","displayFont":"\"Great Vibes\", cursive","displayFontStyle":"font-weight: 400;","bodyFont":"\"Geologica\", sans-serif","ornament":"hairline"},"sections":[{"type":"hero","variant":"centered","copy":{"eyebrow":"Просимо честі вашої присутності","connector":"та"}},{"type":"countdown","variant":"minimal","bg":"background","copy":{"title":"Пригода починається"}},{"type":"story","variant":"alternating","copy":{"title":"Наша історія кохання"},"imageAspect":"3/4"},{"type":"colors","variant":"circles","copy":{"title":"Кольори весілля"}},{"type":"events","variant":"dashed","copy":{"title":"Програма подій"}},{"type":"venue","variant":"centered","copy":{"title":"Місце проведення","closing":"Чекаємо на вас!"}}]}',
  '{"hisName":"","herName":"","weddingDate":"","weddingPlace":"","venue":{"label":"","mapsUrl":""},"loveStory":{"moments":[]},"events":[],"weddingColors":[],"templateColors":{"primary":"#FBF7EE","text":"#2C2416","accent":"#D4A574"}}'
),
(
  'modern',
  'Модерн мінімал',
  'Чистий мінімалізм у зелених відтінках',
  '{"id":"modern","name":"Модерн мінімал","description":"Чистий мінімалізм у зелених відтінках","defaultColors":{"primary":"#F4F7F1","text":"#1F3A2E","accent":"#4F7B5F"},"thumbnail":{"bg":"#F4F7F1","text":"#1F3A2E","accent":"#4F7B5F","swatch1":"#E8EFE4","swatch2":"#A7BFA3","swatch3":"#4F7B5F","fontClass":"thumb-script-modern","headerText":"Софія & Михайло","fontFaces":"@import url(''https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300&display=swap''); .thumb-script-modern { font-family: \"Cormorant Garamond\", serif; font-weight: 300; letter-spacing: -0.02em; }"},"theme":{"fontImports":"https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600&family=Cormorant+Garamond:wght@300;400;500&display=swap","background":"#F4F7F1","surface":"#E8EFE4","displayFont":"\"Cormorant Garamond\", serif","displayFontStyle":"font-weight: 300; letter-spacing: -0.02em;","bodyFont":"\"Inter\", sans-serif","ornament":"none"},"sections":[{"type":"hero","variant":"split","copy":{"connector":"&"}},{"type":"countdown","variant":"ornamented","bg":{"color":"#1F3A2E"},"textColor":"#F4F7F1","accentColor":"#A7BFA3","padDigits":true,"copy":{"title":"Наше весілля вже через"}},{"type":"story","variant":"stacked","bg":"background","copy":{"title":"Наша історія"},"imageFilter":"grayscale(1)"},{"type":"colors","variant":"squares","bg":{"color":"#1F3A2E"},"textColor":"#F4F7F1","accentColor":"#A7BFA3","copy":{"title":"Кольори"}},{"type":"events","variant":"numbered","bg":"background","copy":{"title":"Програма"}},{"type":"venue","variant":"centered","bg":"surface","copy":{"title":"Місце проведення","closing":"Чекаємо на вас"}}]}',
  '{"hisName":"","herName":"","weddingDate":"","weddingPlace":"","venue":{"label":"","mapsUrl":""},"loveStory":{"moments":[]},"events":[],"weddingColors":[],"templateColors":{"primary":"#F4F7F1","text":"#1F3A2E","accent":"#4F7B5F"}}'
),
(
  'floral',
  'Ботанічний мінімал',
  'Витончений мінімалізм із ботанічною графікою на кремовому тлі',
  '{"id":"floral","name":"Ботанічний мінімал","description":"Витончений мінімалізм із ботанічною графікою на кремовому тлі","defaultColors":{"primary":"#F4EFE6","text":"#1A1A1A","accent":"#8C7355"},"thumbnail":{"bg":"#F4EFE6","text":"#1A1A1A","accent":"#1A1A1A","swatch1":"#F4EFE6","swatch2":"#D9D2C2","swatch3":"#1A1A1A","fontClass":"thumb-script-floral","headerText":"Софія & Михайло","fontFaces":"@import url(''https://fonts.googleapis.com/css2?family=Allura&family=Italiana&display=swap''); .thumb-script-floral { font-family: \"Italiana\", serif; letter-spacing: 0.06em; }"},"theme":{"fontImports":"https://fonts.googleapis.com/css2?family=Allura&family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400&family=Italiana&display=swap","background":"#F4EFE6","surface":"#EDE6D6","displayFont":"\"Italiana\", serif","displayFontStyle":"font-weight: 400; letter-spacing: 0.04em;","bodyFont":"\"Cormorant Garamond\", serif","bodyFontStyle":"letter-spacing: 0.02em;","ornament":"hairline"},"sections":[{"type":"hero","variant":"botanical","copy":{"eyebrow":"Із радістю запрошуємо розділити з нами день, коли ми сказали одне одному «так»","connector":"та"}},{"type":"countdown","variant":"ornamented","bg":"surface","copy":{"title":""}},{"type":"story","variant":"framed","bg":"background","copy":{"title":"Наша історія кохання"},"ornament":"none","imageFilter":"grayscale(0.15)","imageAspect":"4/5"},{"type":"colors","variant":"labelled","bg":"surface","copy":{"title":"Палітра"}},{"type":"events","variant":"dotted-line","bg":"background","ornament":"none","copy":{"title":"Програма дня"}},{"type":"venue","variant":"ornamented","bg":"surface","copy":{"title":"Місце проведення","closing":"З нетерпінням чекаємо на вас"}}]}',
  '{"hisName":"","herName":"","weddingDate":"","weddingPlace":"","venue":{"label":"","mapsUrl":""},"loveStory":{"moments":[]},"events":[],"weddingColors":[],"templateColors":{"primary":"#F4EFE6","text":"#1A1A1A","accent":"#8C7355"}}'
)
ON CONFLICT (slug) DO NOTHING;
